name: Conventional Commits

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    name: conventional-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,docs,test,ci,refactor,perf,chore,revert"