name: secure
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

jobs:
  secure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: x64
      - run: pip install --upgrade virtualenv pip setuptools
      - run: virtualenv .venv
      - run: source .venv/bin/activate; pip install flit==3.8.0
      - run: make install-dev
      - run: make secure